name = "RamseyGrowthModel"
uuid = "d3b58844-8b75-44dd-9e60-01c7b9b67cff"
authors = ["Micha≈Ç Dobranowski <mdbrnowski@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
